config/routes.rb
Rails.application.routes.draw do
  # Index route of the application
  root 'welcome#index'

  # Admin default route 
  get 'admin', to:'admin#index'
  get 'fetch_users', to: 'admin#fetch_users'

  # Disable route of the user by admin
  # get 'disable', to:'admin#disable'
  # Added to disable by ID when rendering users list through datatable
  get '/disable/:id', to: 'admin#disable', as: :disable

  # Callback routes after omniauth authentication
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }
end

app/views/layouts/_messages.html.erb
<% if notice %>
    <div class="alert alert-success"><%= notice %></div>
<% end %>
<% if alert %>
    <div class="alert alert-warning"><%= alert %></div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">
    <%= link_to "Social App", root_path, class: "navbar-brand", id: "logo" %>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
            </li>
            <% if @current_user_admin == 'Y' %>
                <li class="nav-item">
                    <%= link_to "Users List", admin_path, class: "nav-link" %>
                </li>
            <% end %>
        <% end %>
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Log out', destroy_user_session_path, class: "nav-link", method: :delete %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
            </li>
        <% end %>
        </ul>
       
    </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Social Application</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>